#!/bin/bash

OPTIONS="$MEMCACHED_EXTRA_PARAMETERS"

if [ -n "${MEMCACHED_MAX_MEMORY}" ]; then
    OPTIONS+=" -m $MEMCACHED_MAX_MEMORY"
fi

if [ -n "${MEMCACHED_MAX_CONNECTIONS}" ]; then
    OPTIONS+=" -c $MEMCACHED_MAX_CONNECTIONS"
fi

# include logging
# OPTIONS+=" -vv >> /var/log/memcached 2>&1"

set -eu
cmd="$1"; shift

exec $cmd "$@" $OPTIONS
